== Getting Started

=== Prerequisites

jPOS-EE-SDK assumes that the following software is installed in your
development environment:

* JDK 1.8 or higher
* A git client 

While jPOS and jPOS-EE can be used in a Windows environment, we develop
it in an Unix environment, so you'll find many useful Unix scripts
with no Windows counterpart. If you use windows, you may choose to install
a Unix-like environment such as http://www.cygwin.com[Cygwin] so you can
make use of the unix scripts directly.

=== Using an IDE

jPOS-EE is known to work with most modern IDEs such as Eclipse,
NetBeans, Jetbrain's IDEA(R). The Gradle configuration uses the
IDEA and Eclipse plugins allowing you to create suitable IDE
configurations by running `gradle idea` or `gradle eclipse`.

=== Using an application server

jPOS-EE is a stand-alone application that runs off jPOS' Q2 container.

We are aware that there are companies and institutions that standardize
on using a given application server or JEE container. That's great, but
jPOS-EE is a stand-alone application. If you master your application
server, you will certainly be able to integrate jPOS-EE, either as a
client EJB application, as a Resource Adapter, a WAR, EAR, etc. In
addition, some application servers have proprietary extensions that
facilitates such integration.

But let us repeat this one more time. jPOS-EE is a stand alone
application. If you know how to run it inside application server XYZ,
that's perfect; if we can make your life easier by doing something on
our end that makes that integration easier, and you have the expertise
in both jPOS-EE and your application server to provide us detailed
instructions on what you need, and the changes won't break any existing
jPOS or jPOS-EE functionality, then we are willing to do so, but if you
decide to go that route, you'll be on your own.

=== Preparing your environment

In this chapter we will work through setting up the development environment consisting of:

* Downloading the jPOS-EE SDK source code using Git.
* Compiling and installing the components locally on your system.

=== Maven coordinates

jPOS-EE modules are regularly published to jPOS' maven repository. You can use its
dependencies by adding

    <repository>
        <id>jpos-ee</id>
        <name>jPOS Maven Repository</name>
        <url>http://jpos.org/maven</url>
    </repository>

to your Maven or

    repositories {
        ...
        maven { url 'http://jpos.org/maven' }
        ...
    }

to your Gradle configuration.

[TIP]
=====
We recommend you use the https://github.com/jpos/jPOS-template[jPOS Template], 
in particular its `multimodule` branch when building jPOS-EE based applications.
=====

=== Downloading the sources

In order to get a copy of it, and keep your copy up-to-date with 
the latest revision, you need to use a Git client.

Git installation instructions for Windows, Linux and MacOS X are available here:
http://help.github.com/set-up-git-redirect[Git Setup].

jPOS-EE is hosted at https://github.com/jpos/jPOS-EE[GitHub]. By visiting
the project page you will be provided information on how to Checkout,
Browse and see a history of changes to the system.

If you are on an Unix/Unix-like environment, an initial checkout would
look something like :-

-------------------------------------------------------------------------
$ git clone https://github.com/jpos/jPOS-EE.git
Cloning into 'jPOS-EE'...
remote: Counting objects: 627, done.
remote: Compressing objects: 100% (355/355), done.
remote: Total 627 (delta 250), reused 528 (delta 151)
Receiving objects: 100% (627/627), 127.72 KiB, done.
Resolving deltas: 100% (250/250), done.
$
-------------------------------------------------------------------------


This will create a new directory ``jPOS-EE'' containing a clone of what's currently in the master branch at our central GitHub repository.

=== Installing the SDK

If you're not using jPOS Maven repo, you can install your dependencies locally
by calling:

    gradle install

If your build completes with ``BUILD SUCCESSFUL'' , you are ready to proceed to create your first project!

[NOTE]
==========================================================================
Gradle just built and installed all of its components into your local Maven
repository, where they can be accessed by any of your projects.

If you have made local changes to the jPOS-EE sources, followed by a call
to `gradle install`, make sure that your `mavenLocal()` repository comes
*before* `http://jpos.org/maven` in your repository list so that dependencies
are taken from your local `$HOME/.m2/repository` directory.

Please note that while this is OK during development, it's a bad practice
if you expect to produce repeatable builds.
==========================================================================

