In our traditional Ant based build system, the developer chooses which modules
to use from the 'opt' directory, and creates symbolic links to the 'modules' directory. The build
system merges them into a flat structure, and does some processing such as:

* Concatenate constants files from all modules into single addressable constant files.
* Create the hibernate configuration file from all the "mapping file" snippets from all the selected modules
* Resolve any property placeholders from all modules using property files

Compiled classes for all selected modules, static definitions for database connections, static constants file(s), etc. are
then used to generate a jar archive (jposee.jar).

With the introduction of Gradle-based jPOS-EE project structure,
we are also introducing a new module system, based on Maven type artifacts.

Some immediate benefits are:

* The SDK is built independently from your project.
* Your project just uses the modules as versioned dependencies. As a result your project's
  footprint is reduced, as now only need to track your code, not all the jPOS-EE dependencies in your version control system.
* The barrier to entry is greatly reduced, since a new developer could setup a
  jPOS-EE project in five minutes.
* No need to track module dependencies.
* Each module contains "sample" configurations used during project setup at runtime.

=== How do modules work?

A module is nothing more than a simple jar artifact with special features.

==== Hibernate Mappings

A Module defines a "module descriptor", stored in */META-INF/org/jpos/ee/modules*. This descriptor
contains the hibernate mapping entries for the persistent entities defined in this module.

Here is an example,

[source,xml]
----
<module name="status">

    <mappings>
        <mapping resource="org/jpos/ee/status/Status.hbm.xml" />
        <mapping resource="org/jpos/ee/status/StatusTag.hbm.xml" />
    </mappings>

</module>
----

It is best practice to name the module descriptor the same as the module name suffixed with the ".xml" extension.

Instead of defining them statically in a central 'hibernate.cfg.xml', the persistent class mappings are
resolved at runtime from all the module descriptors visible in the classpath.

==== Installables

There's a very special resource path, */META-INF/org/jpos/ee/installs*. Any resource stored below that path,
gets installed to the filesystem during the setup process (as shown in the tutorial).

So for example, if we have the 'jposee-core' module as one of our dependencies, and the core modules has the following structure

----
META-INF
`-- org
    `-- jpos
        `-- ee
            `-- installs
                |-- cfg
                |   `-- README.txt
                |-- deploy
                |   |-- 00_logger.xml
                |   `-- 99_sysmon.xml
                `-- log
                    `-- q2.log
----

and we do:

    $ java -jar q2.jar -cli
    q2> setup .

We'd get the following structure copied to our current working directory:

----
.
|-- cfg
|   `-- README.txt
|-- deploy
|   |-- 00_logger.xml
|   `-- 99_sysmon.xml
`-- log
    `-- q2.log
----

If now we added the 'jposee-db-mysql' module as one of our dependencies,
which contains the following structure and ran setup again:

----
META-INF
`-- org
    `-- jpos
        `-- ee
            `-- installs
                `-- cfg
                    `-- db.properties
----

We'd end up with the following files in our filesystem:

----
.
|-- cfg
|   |-- README.txt
|   `-- db.properties
|-- deploy
|   |-- 00_logger.xml
|   `-- 99_sysmon.xml
`-- log
    `-- q2.log
----
