=== Client Simulator

[frame="none",cols="20%,80%"]
|=================================================================
|*What:*| The Client Simulator can be used to fire a suite of unit tests
against an ISO-8583 server. The suite is defined by a set of XML files
representing messages to be sent and their expected responses.
|*When:*| Available in all versions of jPOS-EE.
|*Who:*| The jPOS.org team.
|*How:*| Posted by the jPOS-EE team.
|*Where:*| Directory `modules/client-simulator` available in the repository at GitHub.
|*Why:*| When writing ISO-8583 based server applications the ability to
easily simulate a client is usually very useful. We at jPOS.org use it
as a high level self test for our applications.
|*Status:*| Stable.
|*Dependencies:*| module jpos
|*License:*| <<appendix_license,GNU Affero General Public License version 3>>
|=================================================================

In order to simulate complex ISO-8583 interchanges, the client simulator
uses BSH scripting support to customize the content of ISO-8583 fields
at runtime. This can be used to specify constant values, such as
terminal IDs, merchant IDs, card numbers, as well as dynamic values such
as trace numbers, retrieval reference numbers, pinblocks, key exchange
related stuff, etc.

Let's have a look at the simulator's QBean configuration:

[source,xml]
----------------------------------------------------------------------
    <qbean name="clientSimulator" logger="Q2" realm="client-simulator"
          class="org.jpos.simulator.TestRunner">

     <property name="mux"     value="clientsimulator-mux" />
     <property name="timeout" value="30000" />
     <property name="sessions" value="1" />
----------------------------------------------------------------------

We specify a mux (that's the name of a QMUX running on the same JVM) and
a timeout to wait for a given response. Then we define an initialization
block, i.e:

[source,xml]
---------------------------------------------
     <init>
        import org.jpos.space.*;
        int cnt = 1;
        String terminal = "29110001";
        String merchant = "000000001001";
        String pinblk   = "0123456789ABCDEF";
        Space sp = SpaceFactory.getSpace();
     </init>
---------------------------------------------

The initialization block is basically a BSH script. You can do whatever
you want there, such as defining constants for later use, references to
jPOS objects (such as Space instances, Security module, etc.).

And then the test suite:

[source,xml]
----------------------------------------------------------------------------
     <test-suite>
      <path>cfg/</path>
      <test file="echo" count="10" continue="yes" name="Simple Echo Test" />
      <test file="echo" count="20" continue="yes" name="Simple Echo Test 2">
       <init>
        // optional init script
        // the variable 'testcase'references  _this_ testcase instance
        // the variable 'request' references the ISOMsg that is to be sent
       </init>
       <post>
        // optional post script
        // the variable 'testcase' references  _this_ testcase instance
        // the variable 'response' references the received message
       </post>
      </test>

      <path>cfg/anotherpath</path>
      <test file="mytest">MyTest</test>
      ...
      ...
     </test-suite>
   </qbean>
----------------------------------------------------------------------------

The suite can be separated in different paths, in the previous example,
we assume that there exist two template files named: `cfg/echo_s` and `cfg/echo_r`.

The letter *s* in `cfg/echo_s` stands for *send* and the *r* in `cfg/echo_r`
stands for *receive*.

`cfg/echo_s`:

[source,xml]
---------------------------------------
   <isomsg>
    <field id="0" value="1800" />
    <field id="7" value="1025080500" />
    <field id="11" value="000001" />
    <field id="41" value="29110001" />
   </isomsg>
---------------------------------------

`cfg/echo_r`:

[source,xml]
---------------------------------
   <isomsg>
    <field id="0" value="1810" />
    <field id="39" value="00" />
   </isomsg>
---------------------------------

[TIP]
=====
If the response template file (i.e. `echo_r` in the previous example) is
not present, client simulator blindly sends the message to the server,
ignoring the response. A _response ignored_ note is added to the test log.
=====

In the previous example, we send a 1800 message with some fixed data,
and we expect to receive a 1810 message, with a 00 content in field 39.

While using fixed content may be okay for most fields and test cases,
there are situations where you want to use dynamic content.

Our simulator supports BSH scripts at the field level. Everything that
starts with a bang character (*!*) is considered a script and evaluated as
such, so you can write:

[source,xml]
--------------------------------------------------------------------
   <isomsg>
    <field id="0" value="1800" />
    <field id="7" value="ISODate.getANSIDate (new Date())" />
    <field id="11" value="! System.currentTimeMillis() % 1000000" />
    <field id="41" value="! terminal" />
    <field id="52" value="@ pinblk" />
   </isomsg>
--------------------------------------------------------------------

Please note that in our example terminal is a runtime script variable
that we've defined in our block. The '*@*' characters operates in a
similar way as the '*!*' character, but the resulting value, which is
supposed to be an hexadecimal string, is converted to `byte[]` using
`ISOUtil.hex2byte(String)` in order to produce an `ISOBinaryField`.

The same thing happens at receive time, when we are trying to simulate
voids, reversals, we usually need information received in previous
transactions, such as retrieval reference numbers, audit numbers, etc.
so we can save that information for later use using a receive-time
script:

[source,xml]
---------------------------------------------------
   <isomsg>
    <field id="0" value="1810" />
    <field id="11" value="! previousTrace=value" />
    <field id="37" value="! rrn=value" />
    <field id="39" value="00" />
   </isomsg>
---------------------------------------------------

There's a special variable name called `value` where we put the received
content, so in the previous example, the received retrieval reference
number (field 37), is stored in the variable named `rrn` for later use.

The receive script may optionally return true or false, so we can write
code like this:

[source,xml]
----------------------------------------------------------------------
   <isomsg>
    <field id='39' value='! return value.equals(EXPECTED_RETVALUE)' />
   </isomsg>
----------------------------------------------------------------------

where `EXPECTED_RETVALUE` is initialized in a previous init block.

In fact, the previous example is equivalent to the following:

[source,xml]
-------------------------------------------------
   <isomsg>
    <field id='39' value='! EXPECTED_RETVALUE' />
   </isomsg>
-------------------------------------------------

where the string value of EXPECTED_RETVALUE is used (unless it is a
boolean).

There is a special string **E* to test for echo. To ensure that the
received content of a field is the same as the content we sent, we can
write code like this:

[source,xml]
-------------------------------
   <isomsg>
    <field id='4' value='*E' />
   </isomsg>
-------------------------------

NOTE: The special string \**M* can be used to check for mandatory field
presence, regardless its content. Likewise, **E* can be used to check
for mandatory echo, and \**O* can be used to check for optional echo. You
can also use **A* to check for mandatory _absence_ of a field.

Test cases supports a count attribute that can be used to fire the same
test n times.

It also supports a continue attribute. If continue="yes" then the test
runner would just log an exception if something goes wrong, and it would
continue with the next test.

The default timeout is 60 seconds, but one can specify a different
timeout using the timeout attribute of the testcase element.

At the end, you get a ticket with the test results.

[source,xml]
--------------------------------------------------------
<log realm="org.jpos.simulator.TestRunner" at="......">
  <results>
    Simple Echo Test        [OK] 58ms.
    Simple Echo Test        [OK] 38ms.
    Simple Echo Test        [OK] 70ms.
    Simple Echo Test        [OK] 23ms.
    Simple Echo Test        [OK] 56ms.
    Simple Echo Test        [OK] 24ms.
    Simple Echo Test        [OK] 73ms.
    Simple Echo Test        [OK] 107ms.
    Simple Echo Test        [OK] 20ms.
    Simple Echo Test        [OK] 50ms.
    Simple Echo Test        [OK] 23ms.
    Simple Echo Test        [OK] 24ms.
    Simple Echo Test        [OK] 86ms.
    Simple Echo Test        [OK] 24ms.
    Simple Echo Test        [OK] 24ms.
    Simple Echo Test        [OK] 23ms.
    Simple Echo Test        [OK] 26ms.
    Simple Echo Test        [OK] 21ms.
    Simple Echo Test        [OK] 22ms.
    Simple Echo Test        [OK] 79ms.
    Simple Echo Test 2      [OK] 22ms.
    elapsed server=893ms(62%),
    simulator=526ms(37%), total=1419ms
  </results>
</log>
--------------------------------------------------------

