=== Freemarker Decorator

[frame="none",cols="20%,80%"]
|=================================================================
| *What*         | This module contains a text processor which decorates deployable descriptors for Q2.
| *When*         | Available in all versions of jPOS-EE since v2.0.0.
| *Who*          | The jPOS.org team.
| *Where*        | Directory modules/freemarker-decorator available in git repository at github.
| *Why*          | Install this module to better parameterize your applications.
| *Status*       | Stable.
| *License*      | The jPOS-EE code related to this module is licensed under the
                   <<appendix_license,GNU Affero General Public License version 3>>.
                   FreeMarker (R) itself is released under the BSD
                   license. See http://freemarker.sourceforge.net/docs/app_license.html for
                   details and up-to-date information.
|=================================================================

.Maven Coordinates
[source,xml]
----
        <dependency>
            <groupId>org.jpos.ee</groupId>
            <artifactId>jposee-freemarker-decorator</artifactId>
            <version>${jposee.version}</version>
        </dependency>
----

==== Activation steps

This module remains dormant unless it finds its configuration resource.

In order to activate this module, you need to create a resource in your project residing at
'META-INF/org/jpos/config/Q2-decorator.properties' of your classpath (not the filesystem!).

This file should contain two properties:

[source,ini]
---------------------------------------------------------------------------------------------
config-decorator-class=org.jpos.q2.freemarker.FreemarkerDecorationProvider    <1>
config-files=cfg/config.properties                                            <2>
---------------------------------------------------------------------------------------------
<1> This property tells Q2 to use the FreemarkerDecoratorProvider as its decorator.
<2> This property defines a comma separated list of files which will be used as
    configuration files.

==== Introduction

A typical jPOS-EE application has this standard directory structure:

    .
    |-- cfg
    |   |-- README.txt
    |   `-- db.properties
    |-- deploy
    |   |-- 00_logger.xml
    |   `-- 99_sysmon.xml
    |-- lib
    |-- log
    |   `-- q2.log
    `-- q2.jar

Whatever descriptor you install inside the 'deploy' directory gets immediately deployed.
Once this descriptor is removed, it gets undeployed.

Many of these descriptors require information specific to the target environment, such as
hostnames, ports, ports to listen to, etc. Wouldn't it be great if you could define all of
these in a single location?

The FrameMarker decorator processes *ANY* descriptor in memory giving Q2 the resulting text after processing.
This opens a myriad of opportunities, such as declaring macros, and executing them :)

Let's see an example! Let's assume you have a file 'cfg/config.properties' in your runtime directory that looks like this:

[source,ini]
----
###### GENERAL INFO
NODE = NODE001
######  Environment
env=DEV
######  Ports we listens to
server_listen_port = 9999
######  Target host information
myBankHostPrimary=app.yourbank.com
myBankPortPrimary=2000
###### DEBUG STUFF
debugParticipant=true
----

and we had a deployable file: 'deploy/10_mybank_channel.xml'

[source,xml]
----
<channel-adaptor
      name="mybank-channel-adaptor-pri"
      class="org.jpos.q2.iso.ChannelAdaptor" logger="Q2">

    <channel
          name="mybank-channel-pri"
          packager="org.jpos.iso.packager.GenericPackager"
          class="org.jpos.iso.channel.CSChannel" logger="Q2"
          realm="channel.mybank">

        <property name="timeout" value="3600000"/>
        <property name="host" value="${mybankHostPrimary}"/>
        <property name="port" value="${mybankPortPrimary}"/>
        <property name="packager-config" value="cfg/packager/mybank.xml" />
        <property name="keep-alive" value="true" />
    </channel>

    <in>from-mybank-pri</in>
    <out>to-mybank-pri</out>
    <reconnect-delay>5000</reconnect-delay>
</channel-adaptor>
----

As you can see, we externalized the deployable's configurable over to a central location.

TIP: If you change the settings in the configuration file, you still need to redeploy the deployable (touch it).

But wait, there's more! FreeMarker being a macro processor, brings a lot of nice things for things like TransactionManager descriptors:

For example, ever wanted to have conditional participants?

[source,xml]
----
    [#if debugParticipant == 'true']
    <participant class="org.jpos.transaction.Debug" logger="Q2" realm="debug">
        <property name="checkpoint" value="debug"/>
    </participant>
    [/#if]
----

Or maybe define a macro for things you'll use over and over?

[source,xml]
----
    [#macro OutputToSyslog msg]
    <participant class="com.mycorp.txn.OutputToSyslog"
        logger="Q2" realm="output-to-syslog">
        <property name="node" value="${NODE}"/>
        <property name="message" value="${msg}"/>
    </participant>
    [/#macro]

    <!-- And then invoke it -->
    <group name="myGroup">
        [@OutputToSyslog msg="This is a test"/]
        .... Do some other stuff
    </group>
----
