=== Transaction Support

[frame="none",cols="20%,80%"]
|=================================================================
| *What*         | The 'txn' module contains *Transaction Manager*
                   support code as well as common transaction manager participants.
| *When*         | Available in all versions of jPOS-EE.
| *Who*          | The jPOS.org team.
| *Where*        | Directory modules/txn available in git repository at github.
| *Why*          | This module if useful is your jPOS-EE application uses the *Transaction Manager*.
| *Status*       | Stable.
| *License*      | <<appendix_license,GNU Affero General Public License version 3>>
|=================================================================

.Maven Coordinates
[source,xml]
----
        <dependency>
            <groupId>org.jpos.ee</groupId>
            <artifactId>jposee-txn</artifactId>
            <version>${jposee.version}</version>
        </dependency>
----

There is nothing worse than re-inventing the wheel for every project. With this in mind,
the jPOS team identified a series of activities that were common to almost every
enterprise grade jPOS-EE based project, and created a module to provide the basis for building
great TransactionManager participants that follow best practice patterns.

Instead of showing a boring table with a description of what every component does,
I think an example Transaction Manager instance is in order:

[source,xml]
----------------------------------------------------------------------------------------
<txnmgr name="txnmgr" logger="Q2" class="org.jpos.transaction.TransactionManager">
    <property name="space" value="transient:default"/>
    <property name="queue" value="TXN"/>
    <property name="max-sessions" value="10"/>

    <participant class="org.jpos.transaction.Open" logger="Q2" realm="open-db">     <1>
        <property name="checkpoint" value="db-open"/>
    </participant>

    <participant class="com.mydemo.DemoParticipant"                                 <2>
                 logger="Q2" realm="demo-participant"/>

    <participant class="org.jpos.transaction.Close" logger="Q2" realm="close-db">   <3>
        <property name="checkpoint" value="close"/>
    </participant>
</txnmgr>
----------------------------------------------------------------------------------------
<1> The 'Open' Participant opens a new DB session and transaction.
<2> Our demo participant does some processing
<3> The 'Close' Participant commits or rollbacks the existing transaction based on overall outcome, and closes the session.

In our demo scenario, the transaction manager will open a database session,
execute our DemoParticipant and close the database session (although our DemoParticipant does not need a DB session!).

In case we wanted to add some debugging, we could definitely add to the end of the file:

[source,xml]
----------------------------------------------------------------------------------------
    <participant class="org.jpos.transaction.ProtectDebugInfo"
                 logger="Q2" realm="protect-debug">                                 <1>
        <property name="checkpoint" value="protect-debug-info"/>
        <!-- Wipes entries from context -->
        <property name="wipe-entry" value="PAN"/>
        <property name="wipe-entry" value="EXP"/>
        <!-- Protects contents from any ISOMsg in context -->
        <property name="protect-ISOMsg" value="2"/>
        <property name="protect-ISOMsg" value="35"/>
        <property name="protect-ISOMsg" value="45"/>
        <!-- Wipes contents from any ISOMsg in context -->
        <property name="wipe-ISOMsg" value="48"/>
        <property name="wipe-ISOMsg" value="52"/>
    </participant>

    <participant class="org.jpos.transaction.Debug" logger="Q2" realm="debug">      <2>
        <property name="checkpoint" value="debug"/>
    </participant>
----------------------------------------------------------------------------------------
<1> The 'ProtectDebugInfo' Participant protects sensitive material from logs.
<2> The 'Debug' participant dumps the contents of the context to the log.

This would result in the contents of the context being dumped to the log, protecting
sensitive material on the way.

In case you are wondering what the `DemoParticipant` might look like:

[source,java]
----------------------------------------------------------------------------------------
public class DemoParticipant extends TxnSupport implements MyConstants           <1>
{
    protected int doPrepare(long id, Context ctx) throws Exception               <2>
    {
        ISOMsg message = (ISOMsg) ctx.get(REQUEST);
        ISOSource source = (ISOSource) ctx.get(SOURCE);

        assertNotNull(message,"A valid 'REQUEST' is expected in the context");   <3>
        assertNotNull(source,"A valid 'SOURCE' is expected in the context");
        assertTrue(message.hasField(4),                                          <4>
            "The message needs to have an amount (ISOMsg:4)");

        message.setResponseMTI();

        Random random = new Random(System.currentTimeMillis());
        message.set (37, Integer.toString(Math.abs(random.nextInt()) % 1000000));
        message.set (38, Integer.toString(Math.abs(random.nextInt()) % 1000000));

        if ("000000009999".equals (message.getString (4)))
            message.set (39, "01");
        else
            message.set (39, "00");

        source.send (message);
        return PREPARED | NO_JOIN | READONLY;
    }
    public void commit(long id, Serializable context) { }
    public void abort(long id, Serializable context)  { }
}
----------------------------------------------------------------------------------------
<1> Our demo participant extends TxnSupport, the supporting class provided by this module.
<2> TxnSupport overrides the "prepare" method and delegates to 'doPrepare'
<3> As you can see, not-null assertions are quite easy!
<4> So are boolean assertions.

NOTE: If you are serious about jPOS-EE development involving Transaction Manager, we advise
you to study the `TxnSupport` class further.

=== TxnId

The `txn` module has a handy `TxnId` class that can be used to generate ids in a distributed way.

The id is composed of:

* 1-digit century
* 2-digits year
* 3-digits day of year
* 5-digits second of day
* 3-digits node id
* 5-digits transaction id

A typical ID long value would look like this: `173000348000000001`,
and the `toString()` method would show as `017-300-03480-000-00001`.

`TxnId` also has a handy `toRrn()` method that can be used to create
(and parse) 12-characters strings suitable to be used as retrieval
reference numbers.

`TxnId` can be used instead of UUIDs. It puts less pressure in the database
index and provides chronological order.

[WARNING]
=========
The last two groups, `node-id` and `transaction-id` are supposed to be unique.
transaction-id is easy to get from the transaction manager. `node-id` is a
tricky one, use has to ensure each node has a unique `node-id` to avoid
collisions.
=========

