=== Server Simulator
[[server-simulator]]

[frame="none",cols="20%,80%"]
|=================================================================
| *What:*         | The Server Simulator is an extremely simple, BSH-based simulator
                    that can be used to test ISO-8583 based client software. It listens to
                    port (default 10000), and forwards all incoming requests to a BeanShell
                    based script that can be customized to meet your needs.
| *When:*         | Available in all versions of jPOS-EE.
| *Who:*          | The jPOS.org team.
| *How:*          | Posted by the jPOS-EE team.
| *Where:*        | Directory modules/server-simulator available in the
                    repository at GitHub.
| *Why:*          | When writing ISO-8583 based client applications
                    the ability to easily simulate a server is usually very useful.
| *Status:*       | Stable.
| *Dependencies:* | module jpos
| *License:*      | <<appendix_license,GNU Affero General Public License version 3>>
|=================================================================

The server simulator is a simple QServer with a BSHRequestListener that
handle incoming messages and provide suitable responses.

The default configuration uses an XMLChannel along with an XMLPackager,
but you are free to use any channel/packager combination.

The BSHRequestListener (documented in jPOS programmer's guide) exposes
two objects: message (the incoming ISOMsg) and source (the ISOSource).

Here is the default configuration (05_serversimulator.xml):

[source,xml]
-----------------------------------------------------------------------------
  <server class="org.jpos.q2.iso.QServer" logger="Q2" name="simulator_10000">
  <attr name="port" type="java.lang.Integer">10000</attr>
  <channel class="org.jpos.iso.channel.XMLChannel"
         logger="Q2" packager="org.jpos.iso.packager.XMLPackager">
  </channel>
  <request-listener class="org.jpos.bsh.BSHRequestListener" logger="Q2">
   <property name="source" value="cfg/serversimulator.bsh" />
  </request-listener>
 </server>
-----------------------------------------------------------------------------

And the BSH script looks like this:

[source,java]
----------------------------------------------------------------------------
   message.setResponseMTI ();                                            <1>

   Random random = new Random (System.currentTimeMillis());
   message.set (37, Integer.toString(Math.abs(random.nextInt()) % 1000000));
   message.set (38, Integer.toString(Math.abs(random.nextInt()) % 1000000));

   if ("000000009999".equals (message.getString (4)))                    <2>
       message.set (39, "01");
   else
       message.set (39, "00");

   source.send (message);
----------------------------------------------------------------------------

<1> Sets the response MTI (i.e: 0800/0810, 1201/1220...)
<2> We use the special amount value $99.99 to decline the transaction

TIP: *Never ever* use this simulator even close to a production environment,
or you may end up blindly authorizing transactions.

