Database support is enabled by adding a database backend dependency module to
your project.

For MySQL:
[source,xml]
----
    <dependency>
        <groupId>org.jpos.ee</groupId>
        <artifactId>jposee-db-mysql</artifactId>
        <version>${jposee.version}</version>
    </dependency>
----

For PostgreSQL:
[source,xml]
----
    <dependency>
        <groupId>org.jpos.ee</groupId>
        <artifactId>jposee-db-postgresql</artifactId>
        <version>${jposee.version}</version>
    </dependency>
----

For H2 Embedded database:
[source,xml]
----
    <dependency>
        <groupId>org.jpos.ee</groupId>
        <artifactId>jposee-db-h2</artifactId>
        <version>${jposee.version}</version>
    </dependency>
----

For MS-SQL database:
[source,xml]
----
    <dependency>
        <groupId>org.jpos.ee</groupId>
        <artifactId>jposee-db-mssql</artifactId>
        <version>${jposee.version}</version>
    </dependency>
----

WARNING: Only one of these dependencies should defined in your project.

=== MySQL (R) Support

[frame="none",cols="20%,80%"]
|=================================================================
|*What:*| This module configures Hibernate to use MySQL as its back end.
|*When:*| Available in all versions of jPOS-EE.
|*Who:* |The jPOS.org team.
|*How:* |Posted by the jPOS-EE team.
|*Where:*| Directory modules/db-mysql available in the jPOS-EE GitHub repository.
|*Why:* | An RDBMS back end is required by Hibernate.
|*Status:* | Stable.
|*License:* | The jPOS-EE code related to this module is licensed under the
<<appendix_license,GNU Affero General Public License version 3>>.
Hibernate (R) itself is released under the GNU LGPL v2.1
license. See http://hibernate.org/356.html[Hibernate's License FAQ] for
details and up-to-date information. The MySQL JDBC connector is licensed
under the GNU GPL license. See
http://dev.mysql.com/downloads/connector/j/5.1.html[Connector/J page].
|=================================================================

Upon running 'setup', your runtime directory will contain a file: cfg/db.properties.

[source,ini]
----
hibernate.connection.username=sa                                           <1>
hibernate.connection.password=password                                     <2>
hibernate.hbm2ddl.auto=update                                              <3>
#
hibernate.connection.url=jdbc:mysql://localhost/jposee?autoReconnect=true  <4>
hibernate.connection.driver_class=com.mysql.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
----
<1> Replace value with your database username
<2> Replace value with your database password
<3> Makes hibernate automatically update the contents of the DB to match
    the entities defined. This is good to keep during development, but should
    be set to *NONE* in a production environment.
<4> Replace the host and database (jposee) to match your database settings.

NOTE: You want to change those defaults.

=== PostgreSQL (R) support

[frame="none",cols="20%,80%"]
|=================================================================
|*What:*| This module configures Hibernate to use PostgreSQL as its back end.
|*When:*| Available starting in jPOS-EE v1r104.
|*Who:* | The jPOS.org team.
|*How:* |Posted by the jPOS-EE team.
|*Where:* | Directory modules/db-postgresql available in the jPOS-EE GitHib repository.
|*Why:* |An RDBMS back end is required by Hibernate.
|*Status:*| Stable.
|*License:*| The jPOS-EE code related to this module is licensed under the
<<appendix_license,GNU Affero General Public License version 3>>. As
of jPOS-EE v1r98, Hibernate (R) itself is released under the GNU LGPL v2.1
license. See http://hibernate.org/356.html[Hibernate's License FAQ] for
details and up-to-date information. The PostgreSQL JDBC connector is
licensed under the BSD license. See
http://jdbc.postgresql.org/license.html[Postgresql.org].
|=================================================================

Upon running 'setup', your runtime directory will contain a file: cfg/db.properties.

[source,ini]
----
hibernate.connection.username=sa                                         <1>
hibernate.connection.password=password                                   <2>
hibernate.hbm2ddl.auto=update                                            <3>
hibernate.connection.url=jdbc:postgresql://localhost:5432/jposee         <4>
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
----
<1> Replace value with your database username
<2> Replace value with your database password
<3> Makes hibernate automatically update the contents of the DB to match
    the entities defined. This is good to keep during development, but should
    be set to *NONE* in a production environment.
<4> Replace the host and database (jposee) to match your database settings.

NOTE: You want to change those defaults.

=== H2 Embedded Database support

[frame="none",cols="20%,80%"]
|=================================================================
|*What:*| This module configures Hibernate to use H2 as its back end.
|*When:*| Available in all versions of jPOS-EE since v2.0.0.
|*Who:* | The jPOS.org team.
|*How:* |Posted by the jPOS-EE team.
|*Where:* | Directory modules/db-h2 available in the jPOS-EE GitHib repository.
|*Why:* |An RDBMS back end is required by Hibernate.
|*Status:*| Stable.
|*License:*| The jPOS-EE code related to this module is licensed under the
<<appendix_license,GNU Affero General Public License version 3>>. As
of jPOS-EE v1r98, Hibernate (R) itself is released under the GNU LGPL v2.1
license. See http://hibernate.org/356.html[Hibernate's License FAQ] for
details and up-to-date information. The H2 JDBC connector is
licensed under the EPL license. See
http://www.h2database.com/html/license.html[h2database.com].
|=================================================================

Upon running 'setup', your runtime directory will contain a file: cfg/db.properties.

[source,ini]
----
hibernate.connection.username=sa                                         <1>
hibernate.connection.password=                                           <2>
hibernate.hbm2ddl.auto=update                                            <3>
hibernate.connection.url=jdbc:h2:./data/jposee;LOCK_TIMEOUT=5000         <4>
hibernate.connection.driver_class=org.h2.Driver
hibernate.dialect=org.hibernate.dialect.H2Dialect
----
<1> Replace value with your database username
<2> Replace value with your database password
<3> Makes hibernate automatically update the contents of the DB to match
    the entities defined. This is good to keep during development, but should
    be set to *NONE* in a production environment.
<4> Replace the host and database (jposee) to match your database settings.

NOTE: You want to change those defaults

=== MSSQL Database support

[frame="none",cols="20%,80%"]
|=================================================================
|*What:*| This module configures Hibernate to use MS-SQL as its back end.
|*When:*| Available since v2.2.4
|*Who:* | The jPOS.org team.
|*How:* |Posted by the jPOS-EE team.
|*Where:* | Directory modules/db-mssql available in the jPOS-EE GitHib repository.
|*Why:* |An RDBMS back end is required by Hibernate.
|*Status:*| Stable.
|*License:*| The jPOS-EE code related to this module is licensed under the
<<appendix_license,GNU Affero General Public License version 3>>. As
of jPOS-EE v1r98, Hibernate (R) itself is released under the GNU LGPL v2.1
license. See http://hibernate.org/356.html[Hibernate's License FAQ] for
details and up-to-date information. The H2 JDBC connector is
licensed under the EPL license. See
http://www.h2database.com/html/license.html[h2database.com].
|=================================================================

Upon running 'setup', your runtime directory will contain a file: cfg/db.properties.

[source,ini]
----

hibernate.connection.username=sa                                               <1>
hibernate.connection.password=password                                         <2>
hibernate.hbm2ddl.auto=update                                                  <3>
hibernate.connection.url=jdbc:sqlserver://localhost:1433;databaseName=jposee   <4>
hibernate.connection.driver_class=com.microsoft.sqlserver.jdbc.SQLServerDriver
hibernate.dialect=org.hibernate.dialect.SQLServerDialect                       <5>
----
<1> Replace value with your database username
<2> Replace value with your database password
<3> Makes hibernate automatically update the contents of the DB to match
    the entities defined. This is good to keep during development, but should
    be set to *NONE* in a production environment.
<4> Replace the host and database (jposee) to match your database settings.
<5> `SQLServer2012Dialect` is also available.

NOTE: You want to change those sample defaults

