=== Five minute tutorial

==== Initial setup, jPOS project

Once you have jPOS-EE installed, in order to create your own project, 
you can take advantage of our companion ``jPOS Template''.

Download the latest copy of the jPOS Template
in `zip` (https://github.com/jpos/jPOS-template/archive/master.zip)
or `tar.gz` format (https://github.com/jpos/jPOS-template/archive/master.tar.gz).

Move the directory `jPOS-template-master` into your desired project name, i.e.: ``myjposproject''.

For an initial sanity test, let's build a simple jPOS application first before moving to jPOS-EE.

Call `gradle installApp` (or `gradlew installApp` if you don't have Gradle installed)

Then go to the directory `build/install/myjposproject/bin` and you will find a script called `q2`
(along with a Windows version `q2.bat`). Running it should start jPOS, that you can stop using `Ctrl-C`.

Here is a full transcript of this session:

------------------------------
$ cd /tmp 
$ wget https://github.com/jpos/jPOS-template/archive/master.tar.gz
...
...
Saving to: `master.tar.gz'

$ tar zxvf master.tar.gz
x jPOS-template-master/
x jPOS-template-master/.gitignore
x jPOS-template-master/COPYRIGHT
x jPOS-template-master/LICENSE
x jPOS-template-master/README.md
x jPOS-template-master/build.gradle
x jPOS-template-master/gradle/
...
...
...

$ mv jPOS-template-master myjposproject
$ cd myjposproject
$ ./gradlew installApp
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:installApp

BUILD SUCCESSFUL

$ build/install/myjposproject/bin/q2

...
...
<log realm="Q2.system" at="Fri Jan 25 18:30:37 UYST 2013.335">
  <info>
   deploy:/private/tmp/myjposproject/build/install/myjposproject/deploy/99_sysmon.xml
  </info>
</log>
...
...
------------------------------

The jPOS template creates a standard jPOS application with its 
`lib`, `deploy`, `cfg` and `log` directories that you can review in the 
`build/install/myjposproject` directory.


==== Adding a jPOS-EE Module

Now lets add a jPOS-EE module. We'll start with a simple one, the <<server-simulator, Server Simulator>>.

Edit `build.gradle` and add the following dependency:

----------------
compile group:'org.jpos.ee', 
   name:'jposee-server-simulator', 
   version:'2.0.2-SNAPSHOT'
----------------

so that the dependencies would look like this:

----------------
dependencies {
    compile group:'org.jpos', name:'jpos', version:'1.9.2'
    compile group:'org.jpos.ee', 
      name:'jposee-server-simulator', 
      version:'2.0.2-SNAPSHOT'
    testCompile group:'junit', name:'junit', version:'4.8.2'
}
----------------

If you build again the system by calling `gradle installApp` and you 
review the generated `lib` directory now in `build/install/myjposproject/lib`
you'll see two new libraries:

* `jposee-core-2.0.2-SNAPSHOT.jar` and
* `jposee-server-simulator-2.0.2-SNAPSHOT.jar`

==== Pulling configuration from modules

Now a little hack: jPOS-EE modules contain sample configuration files
inside their distributed jars. Those are intended as a reference and need to be
reviewed by the developer, but they provide a good starting point.

If you try the command:

-------------
jar tvf build/install/myjposproject/lib/jposee-server-simulator-2.0.2-SNAPSHOT.jar 
-------------

You'll see content like this:

-------------
 META-INF/
 META-INF/MANIFEST.MF
 META-INF/org/
 META-INF/org/jpos/
 META-INF/org/jpos/ee/
 META-INF/org/jpos/ee/installs/
 META-INF/org/jpos/ee/installs/cfg/       
 META-INF/org/jpos/ee/installs/cfg/serversimulator.bsh         <1>
 META-INF/org/jpos/ee/installs/deploy/
 META-INF/org/jpos/ee/installs/deploy/05_serversimulator.xml   <2>
-------------
<1> Server Simulator configuration script
<2> Server Simulator QBean descriptor

If you try `gradle tasks` you'll see that there's a task called ``installResources'' 
which is defined in `jpos-app.gradle` like this:

[source,groovy]
-------
task installResources(dependsOn: 'classes', type: JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    main = 'org.jpos.q2.install.Install'
    args = ["--outputDir=src/dist"]
}
-------
This basically pulls all the sample configuration files from jPOS-EE modules
and place them into the `src/dist` directory of your application, where you can
edit them, add them to your SCM, etc.

So if we call `gradle installResources` in the previous example, we would endup
with a couple of new files in `src/dist`:

* `src/dist/cfg/serversimulator.bsh`
* `src/dist/deploy/05_serversimulator.xml`

Those files will land in the `build/install/myjposproject` on your next call to `gradle installApp`
or inside your distribution in `build/distributions` the next time you call `gradle dist`.

[TIP]
====================
At this point, you should be able to run `q2` from the install directory and
have a server listening to port 10000 (the default port). It's an XML server
so you can `telnet localhost 10000` and fire an XML message like this.

[source,xml]
--------------
  <isomsg>
   <field id="0" value="0800" />
   <field id="3" value="000000" />
   <field id="11" value="000001" />
   <field id="41" value="00000001" />
   <field id="70" value="901" />
  </isomsg>
--------------

If everything works alright, you should get a 0810 response.
====================

[TIP]
=====
You may want to visit the jPOS http://jpos.org/tutorials[Tutorials] page for
additional tutorials.
=====

